site_name: IGOOR - Official Documentation
site_url: https://igoor-noprofit.github.io/docs/en/
docs_dir: ../../docs/en
site_dir: ../../site/en
use_directory_urls: true

theme:
  name: material
  custom_dir: ../../overrides/
  language: en
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/stylesheets/extra.css

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Fran√ßais
      link: /fr/
      lang: fr

plugins:
  - search:
      lang: en
  - roamlinks

nav:
  - Home: index.md
  - '1 - INSTALLATION': '1 - INSTALLATION/index.md'
  - '2 - CONFIGURATION': '2 - CONFIGURATION/index.md'
  - '3 - USING IGOOR': '3 - USING IGOOR/index.md'
  - '4 - VOICE SYNTHESIS': '4 - VOICE SYNTHESIS/index.md'
  - '5 - VOICE RECOGNITION': '5 - VOICE RECOGNITION/index.md'
  - '6 - MEMORY': '6 - MEMORY/index.md'
  - '7 - INTEGRATION WITH DEVICES': '7 - INTEGRATION WITH DEVICES/index.md'
  - '9 - FAQ AND RESOLUTION OF COMMON PROBLEMS': '9 - FAQ AND RESOLUTION OF COMMON PROBLEMS/index.md'
