site_name: IGOOR - Official Documentation
site_url: https://igoor-noprofit.github.io/docs/en/
docs_dir: ../../docs/en
site_dir: ../../site/en
use_directory_urls: true

theme:
  name: material
  custom_dir: ../../overrides/
  language: en
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/stylesheets/extra.css

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Fran√ßais
      link: /fr/
      lang: fr

plugins:
  - search:
      lang: en
  - roamlinks

nav:
  - Home: index.md
  - '1 - INSTALLATION':
    - index: '1 - INSTALLATION/index.md'
    - '1 - Prerequisites': '1 - INSTALLATION/1 - Prerequisites.md'
    - '2 - Download IGOOR': '1 - INSTALLATION/2 - Download IGOOR.md'
    - '3 - Install IGOOR': '1 - INSTALLATION/3 - Install IGOOR.md'
  - '2 - CONFIGURATION':
    - index: '2 - CONFIGURATION/index.md'
    - '1 - Minimal Configuration': '2 - CONFIGURATION/1 - Minimal Configuration.md'
    - '2 - Preferences - AI': '2 - CONFIGURATION/2 - Preferences - AI.md'
  - '3 - USING IGOOR':
    - index: '3 - USING IGOOR/index.md'
    - '1 - Four Communication Aid Tools': '3 - USING IGOOR/1 - Four Communication Aid Tools.md'
    - '2 - Daily Needs': '3 - USING IGOOR/2 - Daily Needs.md'
    - '3 - Dialogue with interlocutor': '3 - USING IGOOR/3 - Dialogue with interlocutor.md'
    - '4 - Automatic Input': '3 - USING IGOOR/4 - Automatic Input.md'
    - '5 - Quick Buttons': '3 - USING IGOOR/5 - Quick Buttons.md'
  - '4 - VOICE SYNTHESIS':
    - index: '4 - VOICE SYNTHESIS/index.md'
    - '1 - Choosing your TTS voice synthesis system': '4 - VOICE SYNTHESIS/1 - Choosing your TTS voice synthesis system.md'
    - '2 - Cloning IGOOR User\'s Voice': '4 - VOICE SYNTHESIS/2 - Cloning IGOOR User\'s Voice.md'
  - '5 - VOICE RECOGNITION':
    - index: '5 - VOICE RECOGNITION/index.md'
    - 'Local or cloud ASR': '5 - VOICE RECOGNITION/Local or cloud ASR.md'
  - '6 - MEMORY':
    - index: '6 - MEMORY/index.md'
    - '1 - Types of Memory': '6 - MEMORY/1 - Types of Memory.md'
    - '2 - Extracted Memory from Your Documents': '6 - MEMORY/2 - Extracted Memory from Your Documents.md'
    - '3 - Long Term Memory': '6 - MEMORY/3 - Long Term Memory.md'
    - '4 - Short Term Memory': '6 - MEMORY/4 - Short Term Memory.md'
  - '7 - INTEGRATION WITH DEVICES': '7 - INTEGRATION WITH DEVICES/'
  - '9 - FAQ AND RESOLUTION OF COMMON PROBLEMS': '9 - FAQ AND RESOLUTION OF COMMON PROBLEMS/'
