site_name: IGOOR - Documentation Officielle
site_url: https://igoor-noprofit.github.io/docs/fr/
docs_dir: ../../docs/fr
site_dir: ../../site/fr
use_directory_urls: true

theme:
  name: material
  custom_dir: ../../overrides/
  language: fr
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/stylesheets/extra.css

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Fran√ßais
      link: /fr/
      lang: fr

plugins:
  - search:
      lang: fr
  - roamlinks

nav:
  - Accueil: index.md
  - '1 - INSTALLATION': '1 - INSTALLATION/index.md'
  - '2 - CONFIGURATION': '2 - CONFIGURATION/index.md'
  - '3 - UTILISER IGOOR': '3 - UTILISER IGOOR/index.md'
  - '4 - VOIX DE SYNTHESE': '4 - VOIX DE SYNTHESE/index.md'
  - '5 - RECONNAISSANCE VOCALE': '5 - RECONNAISSANCE VOCALE/index.md'
  - '6 - MEMOIRE': '6 - MEMOIRE/index.md'
  - '7 - INTEGRATION AVEC DISPOSITIFS': '7 - INTEGRATION AVEC DISPOSITIFS/index.md'
  - '9 - FAQ ET RESOLUTION DES PROBLEMES COMMUNS': '9 - FAQ ET RESOLUTION DES PROBLEMES COMMUNS/index.md'
